"""
Report generation and download routes.
Generates structured JSON/HTML/PDF reports from analysis data.
Supports emailing PDF reports to the logged-in user.
"""
import json
import logging
from datetime import datetime
from flask import Blueprint, jsonify, Response, current_app
from flask_jwt_extended import jwt_required, get_jwt_identity
from ..database import query_db, execute_db
from ..security import mask_string
from ..pdf_generator import generate_pdf
from ..email_service import send_report_email
from ..demo.demo_loader import is_demo_mode

logger = logging.getLogger(__name__)

reports_bp = Blueprint('reports', __name__)


def _ensure_demo_recommendations(user_id):
    """Auto-run analysis in demo mode if no recommendations exist."""
    if not is_demo_mode():
        return
    count = query_db(
        "SELECT COUNT(*) AS cnt FROM recommendations WHERE user_id = ? AND status = 'ACTIVE'",
        (user_id,), one=True
    )
    if count and count['cnt'] == 0:
        logger.info('Demo mode: auto-running analysis for report (user %s)', user_id)
        try:
            from .analysis import _run_analysis_for_user
            _run_analysis_for_user(user_id)
        except Exception as e:
            logger.error('Auto-analysis for report failed: %s', e)


def _generate_report_data(user_id: str) -> dict:
    """
    Generate a structured report from the user's latest analysis data.
    Report does NOT contain credentials, logs, or raw metrics.
    """
    _ensure_demo_recommendations(user_id)

    # Get user info
    user = query_db(
        "SELECT username, email FROM users WHERE id = ?",
        (user_id,), one=True
    )

    # Get AWS account info
    aws_account = query_db(
        "SELECT account_alias, region, last_synced FROM aws_accounts WHERE user_id = ?",
        (user_id,), one=True
    )

    # Get recommendations
    recommendations = query_db(
        """SELECT rule_id, resource_id, resource_type, recommendation_text,
                  severity, estimated_savings, created_at
           FROM recommendations
           WHERE user_id = ? AND status = 'ACTIVE'
           ORDER BY
               CASE severity WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 WHEN 'LOW' THEN 3 END,
               estimated_savings DESC""",
        (user_id,)
    )

    rec_list = []
    total_savings = 0.0
    severity_counts = {'HIGH': 0, 'MEDIUM': 0, 'LOW': 0}

    for rec in recommendations:
        savings = rec['estimated_savings']
        total_savings += savings
        severity_counts[rec['severity']] = severity_counts.get(rec['severity'], 0) + 1
        rec_list.append({
            'resource': rec['resource_id'],
            'resource_type': rec['resource_type'],
            'issue': rec['rule_id'],
            'suggested_action': rec['recommendation_text'],
            'severity': rec['severity'],
            'estimated_savings': round(savings, 2)
        })

    report = {
        'report_metadata': {
            'title': 'RACE-Cloud Cost Optimization Report',
            'generated_at': datetime.utcnow().isoformat() + 'Z',
            'generated_by': 'RACE-Cloud Platform',
            'report_version': '1.0'
        },
        'account_summary': {
            'account_id': mask_string(aws_account['account_alias'], 4) if aws_account else 'N/A',
            'region': aws_account['region'] if aws_account else 'N/A',
            'analysis_date': aws_account['last_synced'] if aws_account else 'N/A',
            'prepared_for': user['username'] if user else 'N/A'
        },
        'optimization_recommendations': rec_list,
        'summary_statistics': {
            'total_issues_found': len(rec_list),
            'severity_breakdown': severity_counts,
            'total_estimated_monthly_savings': round(total_savings, 2)
        },
        'disclaimer': (
            'This report is generated by RACE-Cloud for advisory purposes only. '
            'No automatic changes have been or will be made to your AWS account. '
            'All recommendations should be reviewed by your team before implementation. '
            'Cost savings are estimates based on current pricing and usage patterns.'
        )
    }

    return report


def _generate_html_report(report_data: dict) -> str:
    """Generate a downloadable HTML report from structured data."""
    recs = report_data.get('optimization_recommendations', [])
    summary = report_data.get('summary_statistics', {})
    account = report_data.get('account_summary', {})
    meta = report_data.get('report_metadata', {})

    severity_colors = {'HIGH': '#ef4444', 'MEDIUM': '#f59e0b', 'LOW': '#3b82f6'}

    rec_rows = ''
    for i, rec in enumerate(recs, 1):
        color = severity_colors.get(rec['severity'], '#6b7280')
        rec_rows += f"""
        <tr>
            <td>{i}</td>
            <td><code>{rec['resource']}</code></td>
            <td>{rec['resource_type']}</td>
            <td>{rec['suggested_action']}</td>
            <td><span style="background:{color};color:#fff;padding:2px 10px;border-radius:12px;font-size:12px;">{rec['severity']}</span></td>
            <td style="text-align:right;font-weight:600;">${rec['estimated_savings']:.2f}</td>
        </tr>"""

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RACE-Cloud Optimization Report</title>
    <style>
        * {{ margin:0; padding:0; box-sizing:border-box; }}
        body {{ font-family: 'Segoe UI', system-ui, sans-serif; background:#f8fafc; color:#1e293b; line-height:1.6; }}
        .container {{ max-width:900px; margin:0 auto; padding:40px 24px; }}
        .header {{ background:linear-gradient(135deg,#1e40af,#7c3aed); color:#fff; padding:40px 32px; border-radius:16px; margin-bottom:32px; }}
        .header h1 {{ font-size:28px; font-weight:700; margin-bottom:8px; }}
        .header p {{ opacity:0.9; font-size:14px; }}
        .card {{ background:#fff; border-radius:12px; padding:24px; margin-bottom:20px; box-shadow:0 1px 3px rgba(0,0,0,0.08); }}
        .card h2 {{ font-size:18px; font-weight:600; margin-bottom:16px; color:#1e293b; border-bottom:2px solid #e2e8f0; padding-bottom:8px; }}
        .info-grid {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(200px,1fr)); gap:12px; }}
        .info-item {{ padding:12px; background:#f8fafc; border-radius:8px; }}
        .info-item label {{ font-size:12px; color:#64748b; text-transform:uppercase; letter-spacing:0.5px; display:block; }}
        .info-item span {{ font-size:16px; font-weight:600; color:#1e293b; }}
        .stats {{ display:grid; grid-template-columns:repeat(auto-fit,minmax(180px,1fr)); gap:16px; margin-bottom:24px; }}
        .stat-card {{ text-align:center; padding:20px; border-radius:12px; }}
        .stat-card.savings {{ background:linear-gradient(135deg,#059669,#10b981); color:#fff; }}
        .stat-card.high {{ background:#fef2f2; border:1px solid #fecaca; }}
        .stat-card.medium {{ background:#fffbeb; border:1px solid #fed7aa; }}
        .stat-card.low {{ background:#eff6ff; border:1px solid #bfdbfe; }}
        .stat-card .number {{ font-size:32px; font-weight:700; }}
        .stat-card .label {{ font-size:13px; margin-top:4px; }}
        table {{ width:100%; border-collapse:collapse; font-size:14px; }}
        th {{ background:#f8fafc; text-align:left; padding:12px 16px; font-weight:600; color:#475569; border-bottom:2px solid #e2e8f0; }}
        td {{ padding:12px 16px; border-bottom:1px solid #f1f5f9; vertical-align:top; }}
        tr:hover {{ background:#f8fafc; }}
        code {{ background:#f1f5f9; padding:2px 6px; border-radius:4px; font-size:13px; color:#7c3aed; }}
        .disclaimer {{ background:#fefce8; border:1px solid #fde68a; border-radius:12px; padding:20px; margin-top:24px; font-size:13px; color:#92400e; }}
        .footer {{ text-align:center; margin-top:32px; color:#94a3b8; font-size:13px; }}
        @media print {{
            body {{ background:#fff; }} .container {{ padding:20px; }}
            .header {{ border-radius:0; }} .card {{ box-shadow:none; border:1px solid #e2e8f0; }}
        }}
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>☁️ RACE-Cloud Optimization Report</h1>
            <p>Cloud-Native Resource Monitoring & Cost Optimization Platform</p>
            <p style="margin-top:12px;font-size:13px;">Generated: {meta.get('generated_at', 'N/A')}</p>
        </div>

        <div class="card">
            <h2>📋 Account Summary</h2>
            <div class="info-grid">
                <div class="info-item">
                    <label>Account ID</label>
                    <span>{account.get('account_id', 'N/A')}</span>
                </div>
                <div class="info-item">
                    <label>Region</label>
                    <span>{account.get('region', 'N/A')}</span>
                </div>
                <div class="info-item">
                    <label>Analysis Date</label>
                    <span>{account.get('analysis_date', 'N/A')}</span>
                </div>
                <div class="info-item">
                    <label>Prepared For</label>
                    <span>{account.get('prepared_for', 'N/A')}</span>
                </div>
            </div>
        </div>

        <div class="stats">
            <div class="stat-card savings">
                <div class="number">${summary.get('total_estimated_monthly_savings', 0):.2f}</div>
                <div class="label">Estimated Monthly Savings</div>
            </div>
            <div class="stat-card high">
                <div class="number" style="color:#ef4444;">{summary.get('severity_breakdown', {}).get('HIGH', 0)}</div>
                <div class="label" style="color:#991b1b;">High Severity</div>
            </div>
            <div class="stat-card medium">
                <div class="number" style="color:#f59e0b;">{summary.get('severity_breakdown', {}).get('MEDIUM', 0)}</div>
                <div class="label" style="color:#92400e;">Medium Severity</div>
            </div>
            <div class="stat-card low">
                <div class="number" style="color:#3b82f6;">{summary.get('severity_breakdown', {}).get('LOW', 0)}</div>
                <div class="label" style="color:#1e40af;">Low Severity</div>
            </div>
        </div>

        <div class="card">
            <h2>🔍 Optimization Recommendations ({summary.get('total_issues_found', 0)} Issues Found)</h2>
            {'<table><thead><tr><th>#</th><th>Resource</th><th>Type</th><th>Recommendation</th><th>Severity</th><th>Est. Savings/mo</th></tr></thead><tbody>' + rec_rows + '</tbody></table>' if rec_rows else '<p style="color:#64748b;text-align:center;padding:32px;">No optimization issues found. Your AWS resources are well-configured! ✅</p>'}
        </div>

        <div class="disclaimer">
            <strong>⚠️ Advisory Disclaimer:</strong><br>
            {report_data.get('disclaimer', '')}
        </div>

        <div class="footer">
            <p>RACE-Cloud Platform — Academic SGP Project</p>
            <p>Report Version {meta.get('report_version', '1.0')}</p>
        </div>
    </div>
</body>
</html>"""

    return html


# ── Routes ─────────────────────────────────────────────────────────────────────

@reports_bp.route('/latest', methods=['GET'])
@jwt_required()
def get_latest_report():
    """Generate and return the latest report as JSON."""
    user_id = get_jwt_identity()

    report_data = _generate_report_data(user_id)

    # Store report
    aws_account = query_db(
        "SELECT id FROM aws_accounts WHERE user_id = ?",
        (user_id,), one=True
    )

    if aws_account:
        execute_db(
            "INSERT INTO reports (user_id, aws_account_id, report_data_json) VALUES (?, ?, ?)",
            (user_id, aws_account['id'], json.dumps(report_data))
        )

    return jsonify(report_data), 200


@reports_bp.route('/download', methods=['GET'])
@jwt_required()
def download_report():
    """Download the report as an HTML file."""
    user_id = get_jwt_identity()

    report_data = _generate_report_data(user_id)
    html_content = _generate_html_report(report_data)

    timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    filename = f'RACE-Cloud_Report_{timestamp}.html'

    return Response(
        html_content,
        mimetype='text/html',
        headers={
            'Content-Disposition': f'attachment; filename={filename}'
        }
    )


@reports_bp.route('/download-pdf', methods=['GET'])
@jwt_required()
def download_pdf_report():
    """
    Generate and download the report as a PDF file.
    PDF is built in-memory using ReportLab — no temp files.
    The PDF contains ONLY analysis output, never credentials.
    """
    user_id = get_jwt_identity()

    report_data = _generate_report_data(user_id)

    try:
        pdf_bytes = generate_pdf(report_data)
    except Exception as e:
        current_app.logger.error(f'PDF generation failed: {e}')
        return jsonify({'error': 'Failed to generate PDF report'}), 500

    timestamp = datetime.utcnow().strftime('%Y%m%d_%H%M%S')
    filename = f'racecloud_cost_report_{timestamp}.pdf'

    return Response(
        pdf_bytes,
        mimetype='application/pdf',
        headers={
            'Content-Disposition': f'attachment; filename={filename}'
        }
    )


@reports_bp.route('/email', methods=['POST'])
@jwt_required()
def email_report():
    """
    Generate a PDF report and email it to the logged-in user.
    1. Generates report data from latest analysis
    2. Builds PDF in-memory
    3. Sends email with PDF attachment via SMTP
    The email body includes a short summary of findings.
    """
    user_id = get_jwt_identity()

    # Get user info for email
    user = query_db(
        "SELECT username, email FROM users WHERE id = ?",
        (user_id,), one=True
    )
    if not user or not user['email']:
        return jsonify({'error': 'User email not found'}), 400

    report_data = _generate_report_data(user_id)

    # Check that there is analysis data
    recs = report_data.get('optimization_recommendations', [])
    summary = report_data.get('summary_statistics', {})
    if not recs and summary.get('total_issues_found', 0) == 0:
        # Still allow — report will show "no issues" which is valid
        pass

    # Generate PDF
    try:
        pdf_bytes = generate_pdf(report_data)
    except Exception as e:
        current_app.logger.error(f'PDF generation for email failed: {e}')
        return jsonify({'error': 'Failed to generate PDF report'}), 500

    # Send email
    result = send_report_email(
        recipient_email=user['email'],
        recipient_name=user['username'],
        pdf_bytes=pdf_bytes,
        report_summary=summary
    )

    status_code = 200 if result['success'] else 500
    return jsonify(result), status_code


@reports_bp.route('/history', methods=['GET'])
@jwt_required()
def get_report_history():
    """Get list of previously generated reports."""
    user_id = get_jwt_identity()

    reports = query_db(
        """SELECT id, created_at FROM reports
           WHERE user_id = ?
           ORDER BY created_at DESC
           LIMIT 20""",
        (user_id,)
    )

    return jsonify({
        'reports': [
            {'id': r['id'], 'created_at': r['created_at']}
            for r in reports
        ]
    }), 200
