"""
Email service for RACE-Cloud.
Sends PDF report as an attachment to the logged-in user's email.
Uses Python's built-in smtplib — no external email SDK required.
Credentials are loaded from environment variables (.env file).
"""
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email.mime.text import MIMEText
from email import encoders
from datetime import datetime
from flask import current_app


def _get_email_config() -> dict:
    """Load SMTP configuration from environment / app config."""
    return {
        'host':     os.getenv('SMTP_HOST', 'smtp.gmail.com'),
        'port':     int(os.getenv('SMTP_PORT', '587')),
        'username': os.getenv('SMTP_USERNAME', ''),
        'password': os.getenv('SMTP_PASSWORD', ''),
        'from':     os.getenv('SMTP_FROM_EMAIL', os.getenv('SMTP_USERNAME', '')),
        'use_tls':  os.getenv('SMTP_USE_TLS', 'true').lower() == 'true',
    }


def send_report_email(
    recipient_email: str,
    recipient_name: str,
    pdf_bytes: bytes,
    report_summary: dict
) -> dict:
    """
    Send the PDF optimization report as an email attachment.

    Parameters
    ----------
    recipient_email : str
        The logged-in user's email address (from the users table).
    recipient_name : str
        Display name for the greeting.
    pdf_bytes : bytes
        In-memory PDF content generated by pdf_generator.generate_pdf().
    report_summary : dict
        Summary statistics for the email body text.

    Returns
    -------
    dict  {'success': bool, 'message': str}

    Security Notes
    --------------
    • Only analysis OUTPUT is emailed — never credentials.
    • SMTP credentials are read from .env, never hard-coded.
    • PDF is generated in-memory and attached directly.
    """
    cfg = _get_email_config()

    if not cfg['username'] or not cfg['password']:
        current_app.logger.warning('SMTP credentials not configured — email skipped.')
        return {
            'success': False,
            'message': 'Email not configured. Set SMTP_USERNAME and SMTP_PASSWORD in .env'
        }

    # ── Build summary text for email body ──────────────────────────────────────
    total_issues = report_summary.get('total_issues_found', 0)
    total_savings = report_summary.get('total_estimated_monthly_savings', 0)
    sev = report_summary.get('severity_breakdown', {})
    timestamp = datetime.utcnow().strftime('%B %d, %Y at %H:%M UTC')

    body_text = f"""Hello {recipient_name},

Your RACE-Cloud cost optimization analysis is complete.

────────────────────────────
  ANALYSIS SUMMARY
────────────────────────────
  Total Issues Found  : {total_issues}
  High Severity       : {sev.get('HIGH', 0)}
  Medium Severity     : {sev.get('MEDIUM', 0)}
  Low Severity        : {sev.get('LOW', 0)}
  Est. Monthly Savings: ${total_savings:.2f}
────────────────────────────

The full PDF report is attached to this email.

Important: This report is for advisory purposes only. No changes have been
made to your AWS account. Please review each recommendation before acting.

— RACE-Cloud Platform
   Generated on {timestamp}
"""

    body_html = f"""\
<html>
<body style="font-family: 'Segoe UI', Arial, sans-serif; color: #1e293b; line-height: 1.6;">
<div style="max-width: 560px; margin: 0 auto; padding: 24px;">
  <h2 style="color: #1e40af; margin-bottom: 4px;">RACE-Cloud</h2>
  <p style="color: #64748b; font-size: 14px; margin-top: 0;">Cost Optimization Report</p>
  <hr style="border: none; border-top: 1px solid #e2e8f0;" />

  <p>Hello <b>{recipient_name}</b>,</p>
  <p>Your cost optimization analysis is complete. Here is a quick summary:</p>

  <table style="width: 100%; border-collapse: collapse; font-size: 14px; margin: 16px 0;">
    <tr style="background: #f8fafc;">
      <td style="padding: 10px 14px; border: 1px solid #e2e8f0;"><b>Total Issues</b></td>
      <td style="padding: 10px 14px; border: 1px solid #e2e8f0; text-align: center;">{total_issues}</td>
    </tr>
    <tr>
      <td style="padding: 10px 14px; border: 1px solid #e2e8f0; color: #ef4444;"><b>High Severity</b></td>
      <td style="padding: 10px 14px; border: 1px solid #e2e8f0; text-align: center;">{sev.get('HIGH', 0)}</td>
    </tr>
    <tr style="background: #f8fafc;">
      <td style="padding: 10px 14px; border: 1px solid #e2e8f0; color: #f59e0b;"><b>Medium Severity</b></td>
      <td style="padding: 10px 14px; border: 1px solid #e2e8f0; text-align: center;">{sev.get('MEDIUM', 0)}</td>
    </tr>
    <tr>
      <td style="padding: 10px 14px; border: 1px solid #e2e8f0; color: #3b82f6;"><b>Low Severity</b></td>
      <td style="padding: 10px 14px; border: 1px solid #e2e8f0; text-align: center;">{sev.get('LOW', 0)}</td>
    </tr>
    <tr style="background: #059669; color: #fff;">
      <td style="padding: 12px 14px; border: 1px solid #047857;"><b>Est. Monthly Savings</b></td>
      <td style="padding: 12px 14px; border: 1px solid #047857; text-align: center; font-size: 18px;"><b>${total_savings:.2f}</b></td>
    </tr>
  </table>

  <p>The full PDF report is attached to this email.</p>

  <div style="background: #fefce8; border: 1px solid #fde68a; border-radius: 8px; padding: 14px; font-size: 13px; color: #92400e; margin: 16px 0;">
    <b>Advisory Disclaimer:</b> This report is for informational purposes only.
    No changes have been made to your AWS account.
  </div>

  <hr style="border: none; border-top: 1px solid #e2e8f0;" />
  <p style="font-size: 12px; color: #94a3b8; text-align: center;">
    RACE-Cloud Platform — Academic SGP Project<br/>
    Generated on {timestamp}
  </p>
</div>
</body>
</html>
"""

    # ── Compose email ──────────────────────────────────────────────────────────
    msg = MIMEMultipart('alternative')
    msg['Subject'] = f'RACE-Cloud Cost Optimization Report — {timestamp}'
    msg['From']    = cfg['from']
    msg['To']      = recipient_email

    # Plain-text and HTML parts
    msg.attach(MIMEText(body_text, 'plain'))
    msg.attach(MIMEText(body_html, 'html'))

    # PDF attachment
    pdf_filename = f"racecloud_cost_report_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf_part = MIMEBase('application', 'pdf')
    pdf_part.set_payload(pdf_bytes)
    encoders.encode_base64(pdf_part)
    pdf_part.add_header(
        'Content-Disposition', 'attachment', filename=pdf_filename
    )
    msg.attach(pdf_part)

    # ── Send ───────────────────────────────────────────────────────────────────
    try:
        server = smtplib.SMTP(cfg['host'], cfg['port'], timeout=30)
        if cfg['use_tls']:
            server.starttls()
        server.login(cfg['username'], cfg['password'])
        server.sendmail(cfg['from'], [recipient_email], msg.as_string())
        server.quit()

        current_app.logger.info(f'Report email sent to {recipient_email}')
        return {'success': True, 'message': f'Report emailed to {recipient_email}'}

    except smtplib.SMTPAuthenticationError:
        current_app.logger.error('SMTP authentication failed')
        return {'success': False, 'message': 'Email authentication failed. Check SMTP credentials.'}
    except smtplib.SMTPException as e:
        current_app.logger.error(f'SMTP error: {e}')
        return {'success': False, 'message': f'Email sending failed: {str(e)}'}
    except Exception as e:
        current_app.logger.error(f'Email error: {e}')
        return {'success': False, 'message': 'Unexpected error sending email.'}
